baseUrl: "https://kewbi.sh/blog"
title: "Yours, Kewbish"
defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
    params:
      lang: en
  fr:
    languageName: Français
    weight: 2
    params:
      lang: fr
      disabledKinds: ["home", "section", "taxonomy", "404"]
MetaDataFormat: "yaml"
theme: "yk"
relativeUrls: true
disableKinds: ["taxonomy"]
publishDir: "docs"
outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
Author:
  name: "Emilie Ma (Kewbish)"
Params:
  cssLink: "https://kewbi.sh/css/main.css"
  fontLinks: |
    <link
      rel="preload"
      as="text/woff2"
      href="https://kewbi.sh/fonts/playfair-display-v30-latin-italic.woff2"
    />
    <link
      rel="preload"
      as="text/woff2"
      href="https://kewbi.sh/fonts/playfair-display-v30-latin-700.woff2"
    />
    <link
      rel="preload"
      as="text/woff2"
      href="https://kewbi.sh/fonts/source-sans-3-v8-latin-regular.woff2"
    />
