baseURL: https://kewbi.sh/blog
title: Yours, Kewbish
defaultContentLanguage: en
theme: yk
disableKinds:
  - taxonomy
publishDir: docs
languages:
  en:
    languageCode: en-ES
    languageName: English
    weight: 1
  fr:
    languageCode: fr-FR
    languageName: Français
    weight: 2
    disableKinds:
      - home
      - section
      - taxonomy
      - "404"
outputs:
  home:
    - html
    - rss
  section:
    - html
params:
  cssLink: https://kewbi.sh/css/main.css
  fontLinks: |
    <link
      rel="preload"
      as="text/woff2"
      href="https://kewbi.sh/fonts/playfair-display-v30-latin-italic.woff2"
    />
    <link
      rel="preload"
      as="text/woff2"
      href="https://kewbi.sh/fonts/playfair-display-v30-latin-700.woff2"
    />
    <link
      rel="preload"
      as="text/woff2"
      href="https://kewbi.sh/fonts/source-sans-3-v8-latin-regular.woff2"
    />
canonifyURLs: true
