baseURL: "kewbish.github.io"
title: "Yours, Kewbish"
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
theme: "yk"
relativeUrls: true
disableKinds: ["taxonomy", "taxonomyTerm"]
publishDir: "docs"